### PR TITLE
Update Chinese translation.

### PR DESCRIPTION
**Pull request by VergeDX**
Optimized Chinese translation.

~~The original translation seems to be machine translation?~~

### CODE REVIEW

**Comment by VergeDX** [comment]
@Jeremiidesu 
@Mark9870

**Comment by Erinaaaaaaa** [comment]
I can't check the pull request right now (class takes too much time). Will review and stuff during the weekend

**Comment by VergeDX** [comment]
OK
Thank you.

**Comment by Erinaaaaaaa** [comment]
merged!

**Pull request merged**
